# Generated by Django 3.2.9 on 2022-02-05 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FamilyPortal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ta_test',
        ),
    ]
