# Generated by Django 3.2.9 on 2022-02-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ma_uid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=64)),
                ('member', models.CharField(max_length=64)),
            ],
        ),
    ]
