# Generated by Django 3.2.9 on 2022-02-02 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ma_listType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listType', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ma_status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ma_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('table', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ma_uid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=64)),
                ('member', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ta_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid_id', models.IntegerField(default=0)),
                ('table_id', models.IntegerField(default=0)),
                ('inTable_id', models.IntegerField(default=0)),
                ('status_id', models.IntegerField(default=0)),
                ('updateDay', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
