# Generated by Django 3.2.9 on 2022-02-05 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ma_uid',
        ),
    ]
