# Generated by Django 3.2.9 on 2022-02-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ta_list',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='未タイトル', max_length=255)),
                ('content', models.CharField(max_length=255, null=True)),
                ('listType_id', models.IntegerField(default=0)),
                ('flg_1', models.IntegerField(default=0)),
                ('flg_2', models.IntegerField(default=0)),
                ('flg_3', models.IntegerField(default=0)),
                ('flg_4', models.IntegerField(default=0)),
                ('flg_5', models.IntegerField(default=0)),
                ('flg_6', models.IntegerField(default=0)),
                ('flg_7', models.IntegerField(default=0)),
                ('flg_8', models.IntegerField(default=0)),
                ('flg_9', models.IntegerField(default=0)),
                ('flg_10', models.IntegerField(default=0)),
            ],
        ),
    ]
